# EDIF input is generated by arp_passthru.lua (svd.write_netlist_edif).
# Override: set EDIF=/path before sourcing, else defaults to the /tmp work area.
set EDIF [expr {[info exists ::env(EDIF)] ? $::env(EDIF) : "/tmp/arp_edif_dir/top.edf"}]
read_edif $EDIF
link_design -part xc7vx485tffg1761-2 -top top
read_xdc /home/jonathan/v7-johnson-demo/ethsoc/r0_pins.xdc
read_xdc [file join [file dirname [info script]] .. vc707_flat_clocks.xdc]
puts "=== OPT ==="; opt_design
puts "=== PLACE ==="; place_design
puts "=== ROUTE ==="; route_design
puts [report_route_status -return_string]
write_bitstream -force /tmp/eb/arp_passthru.bit
puts "=== PASSTHRU_DONE ==="
