# Extract the placement of every leaf cell under an eth_macro instance from
# an implemented DCP, as macro-relative BEL+LOC constraints.
#   vivado -mode batch -source extract_eth_macro_locs.tcl \
#          [-tclargs <dcp> <hier-prefix> <out.xdc>]
# defaults: vc707_ethloop.dcp  eth/eth_macro1/  eth_macro_locs.xdc
# (for the harness DCP: eth_macro_harness.dcp  u_macro/  eth_macro_locs.xdc)
set dcp    [lindex $argv 0]
set prefix [lindex $argv 1]
set out    [lindex $argv 2]
if {$dcp eq ""}    { set dcp vc707_ethloop.dcp }
if {$prefix eq ""} { set prefix {eth/eth_macro1/} }
if {$out eq ""}    { set out eth_macro_locs.xdc }

open_checkpoint $dcp

set f [open $out w]
puts $f "# auto-generated by extract_eth_macro_locs.tcl from $dcp (prefix $prefix)"
set n 0
foreach c [get_cells -hierarchical -filter "NAME =~ ${prefix}* && IS_PRIMITIVE"] {
    set loc [get_property LOC $c]
    if {$loc eq ""} { continue }
    set bel [get_property BEL $c]
    set rel [string range $c [string length $prefix] end]
    puts $f "set_property BEL $bel \[get_cells -quiet {$rel}\]"
    puts $f "set_property LOC $loc \[get_cells -quiet {$rel}\]"
    incr n
}
close $f
puts "extract_eth_macro_locs: wrote $n placements to $out"

# sanity: clock/GT primitives (must match the golden GT frame addressing)
foreach c [get_cells -hierarchical -filter "NAME =~ ${prefix}* && (REF_NAME =~ GTXE2* || REF_NAME =~ IBUFDS_GTE2 || REF_NAME =~ BUFG* || REF_NAME =~ MMCM*)"] {
    puts "  anchor: [get_property REF_NAME $c] [get_property LOC $c]  $c"
}
