set_property PACKAGE_PIN E19 [get_ports IO_CLK_P]
set_property IOSTANDARD LVDS [get_ports IO_CLK_P]
set_property PACKAGE_PIN E18 [get_ports IO_CLK_N]
set_property IOSTANDARD LVDS [get_ports IO_CLK_N]
create_clock -period 5.000 -name sysclk [get_ports IO_CLK_P]
set_property PACKAGE_PIN AV40 [get_ports IO_RST]
set_property IOSTANDARD LVCMOS18 [get_ports IO_RST]
set_property PACKAGE_PIN AM39 [get_ports {LED[0]}]
set_property PACKAGE_PIN AN39 [get_ports {LED[1]}]
set_property PACKAGE_PIN AR37 [get_ports {LED[2]}]
set_property PACKAGE_PIN AT37 [get_ports {LED[3]}]
set_property PACKAGE_PIN AR35 [get_ports {LED[4]}]
set_property PACKAGE_PIN AP41 [get_ports {LED[5]}]
set_property PACKAGE_PIN AP42 [get_ports {LED[6]}]
set_property PACKAGE_PIN AU39 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[*]}]
set_property PACKAGE_PIN AU36 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TX]
set_property PACKAGE_PIN AU33 [get_ports UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports UART_RX]
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
